// Import all js dependencies.
import 'popper.js/dist/popper.min'
import 'bootstrap/js/src/util'
import 'bootstrap/js/dist/carousel'
import 'bootstrap/js/dist/dropdown'
import 'bootstrap/scss/bootstrap.scss'
import 'bootstrap/scss/bootstrap-reboot.scss'
import 'bootstrap/scss/bootstrap-grid.scss'
import 'bootstrap/scss/bootstrap-utilities.scss'
import 'animate.css/animate.css'
